monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/api.log"
            level: info
            formatter: 'monolog.formatter.json'
            channels: ["app"]
